<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPluginsPaymentsPagSeguroContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPluginsPaymentsPagSeguroContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPluginsPaymentsPagSeguroAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPluginsPaymentsPagSeguroContentFiles Include="$(SplatDevUmbracoPluginsPaymentsPagSeguroContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPluginsPaymentsPagSeguroContentFiles)" DestinationFiles="@(SplatDevUmbracoPluginsPaymentsPagSeguroContentFiles-&gt;'$(MSBuildProjectDirectory)\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
