<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPluginsSocialMediaLoginContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPluginsSocialMediaLoginContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPluginsSocialMediaLoginAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPluginsSocialMediaLoginContentFiles Include="$(SplatDevUmbracoPluginsSocialMediaLoginContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPluginsSocialMediaLoginContentFiles)" DestinationFiles="@(SplatDevUmbracoPluginsSocialMediaLoginContentFiles-&gt;'$(MSBuildProjectDirectory)\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
