<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPluginsPaymentsBancoInterContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPluginsPaymentsBancoInterContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPluginsPaymentsBancoInterAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPluginsPaymentsBancoInterContentFiles Include="$(SplatDevUmbracoPluginsPaymentsBancoInterContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPluginsPaymentsBancoInterContentFiles)" DestinationFiles="@(SplatDevUmbracoPluginsPaymentsBancoInterContentFiles-&gt;'$(MSBuildProjectDirectory)\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
