<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <PackageIcon>icon.png</PackageIcon>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>SplatDev.Umbraco.Pagination</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>2.0.4</Version>
		<Authors>SplatDev</Authors>
		<Description>Pagination helpers for Umbraco 13 (net8.0) and Umbraco 17 (net10.0)</Description>
		<PackageTags>umbraco pagination</PackageTags>
		<Company>SplatDev Ltda</Company>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/splatdevtech/SplatDev.Umbraco.Plugins</PackageProjectUrl>
		<RepositoryUrl>https://github.com/splatdevtech/SplatDev.Umbraco.Plugins</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="\" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
