<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPlugins2faContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPlugins2faContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPlugins2faAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPlugins2faContentFiles Include="$(SplatDevUmbracoPlugins2faContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPlugins2faContentFiles)" DestinationFiles="@(SplatDevUmbracoPlugins2faContentFiles-&gt;'$(MSBuildProjectDirectory)\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
