<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPluginsWhatsAppContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPluginsWhatsAppContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPluginsWhatsAppAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPluginsWhatsAppContentFiles Include="$(SplatDevUmbracoPluginsWhatsAppContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPluginsWhatsAppContentFiles)" DestinationFiles="@(SplatDevUmbracoPluginsWhatsAppContentFiles-&gt;'$(MSBuildProjectDirectory)\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
