<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPluginsForumsContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPluginsForumsContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPluginsForumsAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPluginsForumsContentFiles Include="$(SplatDevUmbracoPluginsForumsContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPluginsForumsContentFiles)" DestinationFiles="@(SplatDevUmbracoPluginsForumsContentFiles-&gt;'$(MSBuildProjectDirectory)\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
