<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPluginsSocialMediaChannelsPropertyEditorContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPluginsSocialMediaChannelsPropertyEditorContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPluginsSocialMediaChannelsPropertyEditorAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPluginsSocialMediaChannelsPropertyEditorContentFiles Include="$(SplatDevUmbracoPluginsSocialMediaChannelsPropertyEditorContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPluginsSocialMediaChannelsPropertyEditorContentFiles)" DestinationFiles="@(SplatDevUmbracoPluginsSocialMediaChannelsPropertyEditorContentFiles-&gt;'$(MSBuildProjectDirectory)\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
