<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPluginsPhotoGalleryContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPluginsPhotoGalleryContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPluginsPhotoGalleryAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPluginsPhotoGalleryContentFiles Include="$(SplatDevUmbracoPluginsPhotoGalleryContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPluginsPhotoGalleryContentFiles)" DestinationFiles="@(SplatDevUmbracoPluginsPhotoGalleryContentFiles-&gt;'$(MSBuildProjectDirectory)\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
