<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPluginsMemberNotificationsContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPluginsMemberNotificationsContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPluginsMemberNotificationsAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPluginsMemberNotificationsContentFiles Include="$(SplatDevUmbracoPluginsMemberNotificationsContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPluginsMemberNotificationsContentFiles)" DestinationFiles="@(SplatDevUmbracoPluginsMemberNotificationsContentFiles-&gt;'$(MSBuildProjectDirectory)\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
